backend:
  name: github
  repo: Osterlen-Budo/web
  branch: main # Branch to update (optional; defaults to master)

local_backend: true

media_folder: 'static/images'
public_folder: '/images'

collections:
  - name: 'Pages'
    label: 'Sidor'
    folder: 'src/pages'
    create: false
    slug: '{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'page' }
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Datum', name: 'date', widget: 'datetime' }
      - { label: 'Beskrivning', name: 'description', widget: 'string' }
      - { label: 'Text', name: 'body', widget: 'markdown' }

  - name: 'nyheter'
    label: 'Nyheter'
    folder: 'src/pages/news'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'nyhet' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Bild', name: 'image', widget: 'image' }
      - { label: 'Datum', name: 'date', widget: 'datetime' }
      - { label: 'Publicerad', name: 'published', widget: 'boolean', default: true }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'settings'
    label: 'Inställningar'
    delete: false
    editor:
      preview: false
    files:
      - name: 'homepage'
        label: 'Startsida (Hem)'
        file: 'src/pages/homepage.json'
        fields:
          - { label: 'Välkomsttitel', name: 'welcomeTitle', widget: 'string' }
          - { label: 'Välkomsttext', name: 'welcomeText', widget: 'text' }
          - { label: 'Viktigt meddelande (Visas högst upp)', name: 'announcementActive', widget: 'boolean', default: false }
          - { label: 'Meddelandetext', name: 'announcementText', widget: 'string', required: false }
          - { label: 'Meddelandelänk', name: 'announcementLink', widget: 'string', required: false }
          - label: 'Snabblänkar'
            name: 'quickLinks'
            widget: 'list'
            fields:
              - { label: 'Titel', name: 'title', widget: 'string' }
              - { label: 'Beskrivning', name: 'description', widget: 'string' }
              - { label: 'Länk (t.ex. /borjatrana)', name: 'url', widget: 'string' }

      - name: 'termin'
        label: 'Terminstider (Schema)'
        file: 'src/pages/termin.json'
        fields:
          - { label: 'Terminsnamn', name: 'name', widget: 'string', default: 'Höstterminen 2026' }
          - { label: 'Startdatum', name: 'startDate', widget: 'datetime', date_format: 'YYYY-MM-DD', time_format: false, format: 'YYYY-MM-DD', default: '2026-08-17' }
          - { label: 'Slutdatum', name: 'endDate', widget: 'datetime', date_format: 'YYYY-MM-DD', time_format: false, format: 'YYYY-MM-DD', default: '2026-12-10' }
          - { label: 'Sista datum för intag av nybörjare', name: 'intakeEndDate', widget: 'datetime', date_format: 'YYYY-MM-DD', time_format: false, format: 'YYYY-MM-DD', default: '2026-09-30', required: false }
          - { label: 'Informationstext', name: 'infoText', widget: 'string', required: false }






